# Generated by Django 2.1.5 on 2019-04-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_table',
            name='image',
            field=models.ImageField(blank=True, upload_to='expense_image'),
        ),
    ]
