# Generated by Django 2.1.5 on 2019-04-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190416_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder/'),
        ),
    ]
