# Generated by Django 2.1.5 on 2019-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190416_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
