# Generated by Django 2.1.5 on 2019-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190417_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
