# Generated by Django 2.1.5 on 2019-04-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190417_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_table',
            name='image',
        ),
        migrations.AddField(
            model_name='expense_table',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='photo',
        ),
    ]
