# Generated by Django 2.1.5 on 2019-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190417_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
