# Generated by Django 2.1.5 on 2019-04-17 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190417_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_table',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='expense',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.expense_table'),
        ),
    ]
