# Generated by Django 2.1.5 on 2019-04-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20190417_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.expense_table'),
        ),
    ]
