# Generated by Django 2.1.5 on 2019-04-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190417_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense_table',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
