# Generated by Django 2.1.5 on 2019-04-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190418_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_table',
            name='image',
        ),
        migrations.AddField(
            model_name='expense_table',
            name='Img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='photo',
        ),
    ]
