# Generated by Django 2.1.5 on 2019-04-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20190418_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_table',
            name='Img',
        ),
    ]
