# Generated by Django 2.1.5 on 2019-04-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20190418_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_table',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='expense_table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.expense_table'),
        ),
    ]
