# Generated by Django 2.1.5 on 2019-04-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20190419_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='expense_table',
        ),
        migrations.AddField(
            model_name='expense_table',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.photo'),
        ),
    ]
