# Generated by Django 2.1.5 on 2019-04-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20190419_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_table',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.photo'),
        ),
    ]
